trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Building Online Banking System"
  displayName: 'Build Step'

- task: CopyFiles@2
  inputs:
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'website'